name: /Users/elizaevit/miniforge3/envs/llama-env
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8=h99b78c6_7
  - ca-certificates=2025.1.31=hf0a4a13_0
  - libffi=3.4.2=h3422bc3_5
  - liblzma=5.6.4=h39f12f2_0
  - liblzma-devel=5.6.4=h39f12f2_0
  - libsqlite=3.49.1=h3f77e49_1
  - libzlib=1.3.1=h8359307_2
  - ncurses=6.5=h5e97a16_3
  - openssl=3.4.1=h81ee809_0
  - pip=25.0.1=pyh8b19718_0
  - python=3.9.16=hea58f1e_0_cpython
  - readline=8.2=h1d1bf99_2
  - setuptools=75.8.2=pyhff2d567_0
  - tk=8.6.13=h5083fa2_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - xz=5.6.4=h9a6d368_0
  - xz-gpl-tools=5.6.4=h9a6d368_0
  - xz-tools=5.6.4=h39f12f2_0
  - pip:
    - aiofiles==24.1.0
    - aiohappyeyeballs==2.4.6
    - aiohttp==3.11.13
    - aiosignal==1.3.2
    - annotated-types==0.7.0
    - anyio==4.8.0
    - arxiv==2.1.3
    - async-timeout==4.0.3
    - attrs==25.1.0
    - backoff==2.2.1
    - beautifulsoup4==4.13.3
    - certifi==2025.1.31
    - cffi==1.17.1
    - chardet==5.2.0
    - charset-normalizer==3.4.1
    - click==8.1.8
    - coloredlogs==15.0.1
    - contourpy==1.3.0
    - cryptography==44.0.2
    - cycler==0.12.1
    - dataclasses-json==0.6.7
    - diskcache==5.6.3
    - emoji==2.14.1
    - et-xmlfile==2.0.0
    - eval-type-backport==0.2.2
    - exceptiongroup==1.2.2
    - faiss-cpu==1.10.0
    - fastapi==0.115.11
    - feedparser==6.0.11
    - filelock==3.17.0
    - filetype==1.2.0
    - flatbuffers==25.2.10
    - fonttools==4.56.0
    - frozenlist==1.5.0
    - fsspec==2025.2.0
    - h11==0.14.0
    - html5lib==1.1
    - httpcore==1.0.7
    - httpx==0.28.1
    - httpx-sse==0.4.0
    - huggingface-hub==0.29.1
    - humanfriendly==10.0
    - idna==3.10
    - importlib-metadata==8.6.1
    - importlib-resources==6.5.2
    - jinja2==3.1.5
    - joblib==1.4.2
    - jsonpatch==1.33
    - jsonpointer==3.0.0
    - kiwisolver==1.4.7
    - langchain==0.3.20
    - langchain-community==0.3.19
    - langchain-core==0.3.41
    - langchain-huggingface==0.1.2
    - langchain-text-splitters==0.3.6
    - langchainhub==0.1.21
    - langdetect==1.0.9
    - langsmith==0.3.11
    - llama-cpp-python==0.3.7
    - lxml==5.3.1
    - markdown==3.7
    - markupsafe==3.0.2
    - marshmallow==3.26.1
    - matplotlib==3.9.4
    - mpmath==1.3.0
    - multidict==6.1.0
    - mypy-extensions==1.0.0
    - nest-asyncio==1.6.0
    - networkx==3.2.1
    - nltk==3.9.1
    - numpy==1.26.4
    - olefile==0.47
    - onnxruntime==1.19.2
    - opencv-python==4.11.0.86
    - opencv-python-headless==4.11.0.86
    - openpyxl==3.1.5
    - orjson==3.10.15
    - packaging==24.2
    - pandas==2.2.3
    - pdfminer-six==20240706
    - pillow==11.1.0
    - propcache==0.3.0
    - protobuf==6.30.0
    - psutil==7.0.0
    - pyclipper==1.3.0.post6
    - pycparser==2.22
    - pydantic==2.10.6
    - pydantic-core==2.27.2
    - pydantic-settings==2.8.1
    - pymupdf==1.25.3
    - pymupdf4llm==0.0.17
    - pyparsing==3.2.1
    - pypdfium2==4.30.1
    - pytesseract==0.3.13
    - python-box==7.3.2
    - python-dateutil==2.9.0.post0
    - python-dotenv==1.0.1
    - python-iso639==2025.2.18
    - python-magic==0.4.27
    - python-oxmsg==0.0.2
    - pytz==2025.1
    - pyyaml==6.0.2
    - rapidfuzz==3.12.2
    - rapidocr-onnxruntime==1.4.4
    - regex==2024.11.6
    - requests==2.32.3
    - requests-toolbelt==1.0.0
    - safetensors==0.5.3
    - scikit-learn==1.6.1
    - scipy==1.13.1
    - sentence-transformers==3.4.1
    - sgmllib3k==1.0.0
    - shapely==2.0.7
    - six==1.17.0
    - sniffio==1.3.1
    - soupsieve==2.6
    - sqlalchemy==2.0.38
    - sse-starlette==2.2.1
    - starlette==0.46.0
    - starlette-context==0.3.6
    - sympy==1.13.1
    - tabulate==0.9.0
    - tenacity==9.0.0
    - threadpoolctl==3.5.0
    - tokenizers==0.21.0
    - torch==2.6.0
    - tqdm==4.67.1
    - transformers==4.49.0
    - types-requests==2.32.0.20250301
    - typing-extensions==4.12.2
    - typing-inspect==0.9.0
    - typing-inspection==0.4.0
    - tzdata==2025.2
    - unstructured==0.16.25
    - unstructured-client==0.31.1
    - urllib3==2.3.0
    - uvicorn==0.34.0
    - webencodings==0.5.1
    - wrapt==1.17.2
    - yarl==1.18.3
    - zipp==3.21.0
    - zstandard==0.23.0
prefix: /Users/elizaevit/miniforge3/envs/llama-env
